#!/bin/bash

## Copyright ©UDPTeam

## Discord: [URL]https://discord.gg/civ3[/URL]

## Script to keep-alive your DNSTT server domain record query from target resolver/local DNS server

## Run this script excluded from your VPN tunnel (split VPN tunneling mode)

## Run command: ./globe-medrano.sh l

## Repeat dig command loop time (seconds) (positive integer only)

LOOP_DELAY=1  # Set the loop delay to 1 second

## Your DNSTT Nameserver & your Domain `A` Record

NS='ns.dnsttcontabo.acerodns.xyz'
NS1='geim.vantricks.tech'
NS2='ns.jerald.acerodns.xyz'
NS3='ns.kaisen.ismaelsakalam.online'
NS4='ns.dnstt.palaboy.tech'
NS5='hp.bisiro.palaboy.tech'
NS6='ns.arnielvps.acerodns.xyz'
NS7='ns.dnstt01contabo.acerodns.xyz'
NS8='ns.rico.hashi-rama.com'
NS9='ns.dnsttpremium.acerodns.xyz'
NS10='ns.paid.acerodns.xyz'
NS11='james.blu.palaboy.tech'
A='ns.dnsttcontabo.acerodns.xyz'

## Add your DNS here

declare -a HOSTS=('112.198.115.60' '112.198.115.60' '112.198.115.36' '124.6.181.12' '124.6.181.36' '112.198.115.44' '124.6.181.4' '124.6.181.44' '124.6.181.20' '112.198.111.92' '124.6.180.30' '149.112.124.150' '124.6.181.28' '124.6.181.27' '124.6.181.26' '124.6.181.25')

## Linux' dig command executable filepath
## Select value: "CUSTOM|C" or "DEFAULT|D"

DIG_EXEC="DEFAULT"

## if set to CUSTOM, enter your custom dig executable path here

CUSTOM_DIG=/data/data/com.termux/files/home/go/bin/fastdig

######################################
######################################
######################################
######################################
######################################

VER=0.1

# Define text color codes
GREEN='\e[32m'
RED='\e[31m'
RESET='\e[0m'

case "${DIG_EXEC}" in
DEFAULT|D)
    _DIG="$(command -v dig)"
    ;;
CUSTOM|C)
    _DIG="${CUSTOM_DIG}"
    ;;
esac

if [ ! $(command -v ${_DIG}) ]; then
    printf "Dig command failed to run, please install dig (dnsutils) or check DIG_EXEC & CUSTOM_DIG variables inside $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/$(basename "$0") file.\n"
    exit 1
fi

# Function to check DNS resolution and ping DNS nameservers
check() {
    for host in "${HOSTS[@]}"; do
        (timeout -k 3 3 ${_DIG} @"$host" "$A" && echo -e "${GREEN}Host $host: DNS resolution successful.${RESET}") || echo -e "${RED}Host $host: DNS resolution failed.${RESET}"
    done

    # Add DNS nameservers and host IPs to check with ping
    PING_TARGETS=("$NS" "$NS1" "${HOSTS[@]}")

    for target in "${PING_TARGETS[@]}"; do
        if ping -c 1 -W 2 "$target" &>/dev/null; then
            echo -e "${GREEN}Ping to $target: Success.${RESET}"
        else
            echo -e "${RED}Ping to $target: Failed.${RESET}"
        fi
    done
}

echo "DNSTT Keep-Alive script with DNS and host IP ping<Discord @civ3>"
echo "DNS List: ${HOSTS[*]}"
echo "CTRL + C to close script"

while true; do
    check
    echo -SF VPN V2 OFFICIAL-
    sleep ${LOOP_DELAY}
done
