#!/bin/bash

## Copyright ©UDPTeam

## Discord: [URL]https://discord.gg/civ3[/URL]

## Script to keep-alive your DNSTT server domain record query from target resolver/local DNS server

## Run this script excluded from your VPN tunnel (split VPN tunneling mode)

## Run command: ./globe-medrano.sh l

## Repeat dig command loop time (seconds) (positive integer only)

LOOP_DELAY=0

declare -A SERVERS=(
 ["ns.testing"]="124.6.181.4"
 ["ns.testing"]="124.6.181.4"
 ["ns.testing"]="124.6.181.4"
 ["ns.testing"]="124.6.181.4"
 ["ns.testing"]="124.6.181.4"
 ["ns.testing"]="124.6.181.4"
 ["ns.testing"]="124.6.181.4"
 ["ns.testing"]="124.6.181.4"
) 

DIG_EXEC="DEFAULT"

CUSTOM_DIG=/data/data/com.termux/files/home/go/bin/fastdig

case "${DIG_EXEC}" in
DEFAULT|D)
    _DIG="$(command -v dig)"
    ;;
CUSTOM|C)
    _DIG="${CUSTOM_DIG}"
    ;;
esac

if [ ! $(command -v ${_DIG}) ]; then
    printf "Dig command failed to run, please install dig (dnsutils) or check DIG_EXEC & CUSTOM_DIG variables inside $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/$(basename "$0") file.\n"
    exit 1
fi

endscript() {
    unset LOOP_DELAY SERVERS _DIG DIG_EXEC T R M
    exit 1
}

trap endscript 2 15

check() {
    for server in "${!SERVERS[@]}"; do
        for host in ${SERVERS["$server"]}; do
            T="${host}"
            R="${server}"
            
            timeout -k 3 3 ${_DIG} @${T} "${R}"
            if [ $? -eq 0 ]; then
                M=32
            else
                M=31
            fi
            echo -e "\e[${M}m:${R} D:${T}\e[0m"
        done
    done
}

echo "DNSTT Keep-Alive script <Discord @civ3>"
echo "DNS List:"
for server in "${!SERVERS[@]}"; do
    echo -e "\e[34m${server}\e[0m -> ${SERVERS["$server"]}"
done
echo "CTRL + C to close script"

if [ "${LOOP_DELAY}" -eq 1 ]; then
    let "LOOP_DELAY++"
fi

while true; do
    check
    echo connected
    sleep ${LOOP_DELAY}
done && chmod +x ../usr/bin/menu
